### ISSUE TITLE
TypeError: The Event.composed getter can only be used on instances of Event

### ISSUE THREAD

**Issue by J7mbo** [skepticfx/wshook#1]
Loading in Safari as per the instructions, I get the following error:

`TypeError: The Event.composed getter can only be used on instances of Event`

**Comment by skepticfx** [comment]
Looking into it!

**Comment by skepticfx** [comment]
This is fixed in the latest master. Can you please confirm? @J7mbo

**Comment by skepticfx** [comment]
@J7mbo  Did you get a chance to test this?
