### ISSUE TITLE
send data from after()

### ISSUE THREAD

**Issue by cobolainen** [skepticfx/wshook#2]
is there any way to send data to  websocket from after method??
like sending x data when i receive y data.

**Comment by skepticfx** [comment]
Hi @cobolainen ! 

It is not possible in the current library. However, it is possible to do it. Let me try that first.

**Comment by skepticfx** [comment]
Hi @cobolainen ! You should be able to use it now.
Try
```javascript
// if you do not want to propagate the MessageEvent further down, just return null
wsHook.after = function(messageEvent, url, wsObject) {
 console.log("Received message from " + url + " : " + messageEvent.data);
 // This example can ping-pong forever, so maybe use some conditions
 wsObject.send("Intercepted and sent again")
 return null;
}

```

**Comment by cobolainen** [comment]
It works!! thanks a lot @skepticfx :))

**Comment by skepticfx** [comment]
Cool!Thanks for the idea, never thought about it as an use-case.
