### ISSUE TITLE
WsHook not detecting websocket on skribble.io

### ISSUE THREAD

**Issue by downloadpizza** [skepticfx/wshook#8]
Neither Hookish nor WsHook seem to detect WebSockets on skribble.io inside of a userscript
```js
// ==UserScript==
// @name     Skribbl Testing
// @version  1
// @grant    none
// @include https://skribbl.io/*
// @require https://cdn.rawgit.com/skepticfx/wshook/master/wsHook.js
// @run-at document-start
// @grant none
// ==/UserScript==

wsHook.after = function(messageEvent, url, wsObject) {
    console.log("Received message from " + url + " : " + messageEvent.data);
    return messageEvent;
}
```

I assume they are capturing the WebSocket object somehow, but I have not been able to figure out where at this point.
I will conduct further research on this, but would be very happy about your help, as you probably have more experience.

**Comment by skepticfx** [comment]
Thanks for reporting. I'll take a look 👍

**Comment by skepticfx** [comment]
@downloadpizza Seems to work for me. Tested using TamperMonkey with the above UserScript.

![image](https://user-images.githubusercontent.com/803950/113394200-a9c52800-934c-11eb-9ff8-a5e43a29b826.png)


It is possible other UserScripts or chrome extensions are interacting with this?

**Comment by downloadpizza** [comment]
Seems to work for tampermonkey, but neither greasemonkey nor violentmonkey. Not a problem with the library. Didnt think there could be such big differences, but thank you.
